# Generated by Django 4.0.3 on 2022-04-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Car name')),
                ('about', models.TextField(verbose_name='Car about')),
                ('link', models.SlugField(unique=True, verbose_name='Car Link')),
                ('photo', models.ImageField(upload_to='media', verbose_name='Car img')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
